#ifndef SOCIALMEDIA_TYPE_H
#define SOCIALMEDIA_TYPE_H

enum Type {
    BESTIE,
    RELATIVE,
    NORMAL
};

enum Status {
    SUCCESS,
    USER_EXISTS,
    USER1_NOT_FOUND,
    USER2_NOT_FOUND,
    USER1_BANNED,
    USER2_BANNED,
    USERS_LINKED,
    USERS_DELINKED,
    USER_ALREADY_BANNED
};

#endif //SOCIALMEDIA_TYPE_H
